version: "3.9"

services:

  db:
    image: postgres:alpine
    restart: always
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=mediumclone
      - POSTGRES_USER=mediumclone
      - POSTGRES_PASSWORD=mediumclone
    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
